---
- name: Install Kannel dependencies
  apt:
    name: libxml2
    state: present

- name: Install Kannel package
  apt:
    name: kannel
    state: present

- name: Install Kannel extras
  apt:
    name: kannel-extras
    state: present
  when: kannel_install_extras

- name: Enable Kannel Service
  service:
    name: kannel
    enabled: true
  notify:
    - Restart Kannel
