---
- name: Copy monit monitor
  template:
    src: "templates/etc/monit/conf.d/smpp-host-connection.j2"
    dest: "/etc/monit/conf.d/smpp-host-connection"
    mode: 0644
  notify:
    - Reload Monit

- name: Make sure monit exec-scripts directory exists
  file:
    path: "{{ kannel_monit_exec_scripts_path }}"
    state: directory
    mode: 0644

- name: Copy monit connection alert script
  template:
    src: "templates/etc/monit/exec-scripts/smpp-connection-alerts.sh.j2"
    dest: "{{ kannel_monit_exec_scripts_path }}/{{ kannel_monit_exec_script_name }}"
    mode: 0755

- name: Copy Opsgenie alert script
  template:
    src: "templates/etc/monit/exec-scripts/smpp-connection-opsgenie-alerts.sh.j2"
    dest: "{{ kannel_monit_exec_scripts_path }}/{{ kannel_monit_opsgenie_exec_script_name }}"
    mode: 0755
