---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
provisioner:
  name: ansible
verifier:
  name: testinfra
